apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: sales
---
apiVersion: v1
kind: Namespace
metadata:
  name: hku
---
apiVersion: v1
kind: Namespace
metadata:
  name: finance
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-processing